
--Create temporary table
create table ch_git_revision_labeled (id integer, commit text, path text, dir text, component_id integer);

--Load data generated by ch_git_revision.ipynb
COPY ch_git_revision_labeled(id, commit, path, dir, component_id) FROM '/home/taj/Documents/CommonDefects/ch_git_revision_labaled.csv' DELIMITER ',' CSV HEADER;

--Update git_revision_final table
update ch_git_revision_final grf set component_id = grl.component_id from ch_git_revision_labeled grl where grf.commit=grl.commit and grf.path=grl.path and grf.dir=grf.dir;
