\copy (select commit, path, dir, component_id from fx_git_revision_final) to '/home/taj/Documents/CommonDefects/fx_git_revision.csv' delimiter ',' csv header;

--Create temporary table
create table fx_git_revision_labeled (id integer, commit text, path text, dir text, component_id integer);

--Load data generated by fx_git_revision.ipynb
\COPY fx_git_revision_labeled(id, commit, path, dir, component_id) FROM '/home/taj/Documents/CommonDefects/fx_git_revision_labeled.csv' DELIMITER ',' CSV HEADER;

--Update fx_git_revision_final table
update fx_git_revision_final grf set component_id = grl.component_id from fx_git_revision_labeled grl where grf.commit=grl.commit and grf.path=grl.path and grf.dir=grf.dir;
